import {CONFIG} from './config.js';
const BUILD_ID='CA-0920-17';

const players=['Blue','Red','Yellow','White'].map((name,i)=>({name,cash:CONFIG.startCash,tokens:CONFIG.tokens,owned:[],i}));
let turn=0,actions=CONFIG.actions,mode='acquire',selected=null,population=0,jobs=0,setupDraft=true,draftPick=0,pendingBuilding=null,roadSegments=0,actionStart=null,pendingCouncil=null;
const draftOrder=[0,1,2,3,3,2,1,0], rows='ABCDEFG'.split('');
const parcels=[], roads=new Set(), history=[];
for(let r=0;r<CONFIG.height;r++)for(let c=0;c<CONFIG.width;c++)parcels.push({id:rows[r]+(c+1),r,c,owner:null,zone:'greenfield',density:0,building:null,water:r===6,municipal:false});
const plaza={r:1,c:5};
function seed(r,c,zone,building,municipal=false){const p=at(r,c);p.zone=zone;p.density=1;p.building=building;p.municipal=municipal;}
seed(0,5,'residential','Casa'); seed(2,5,'residential','Casa'); seed(1,4,'commercial','Café'); seed(1,6,'commercial','Café'); seed(1,5,'municipal','Plaza Mayor',true);
seed(6,5,'residential','Surf Shack'); // directly south of Plaza on the coast
['H:1:5','H:2:5','V:1:5','V:1:6'].forEach(k=>roads.add(k));

const defs=[['Casa','residential',1],['Café','commercial',1],['Casa','residential',1],['Apartamentos','residential',2],['Tiendas','commercial',2],['Café','commercial',1],['Casa','residential',1],['Hotel','commercial',3],['Apartamentos','residential',2],['Tiendas','commercial',2]];
let nextCardId=defs.length;
function makeCard(d){return {id:nextCardId++,name:d[0],use:d[1],density:d[2],coins:0}}
let market=defs.map((d,i)=>({id:i,name:d[0],use:d[1],density:d[2],coins:0}));
function refillDef(){return defs[Math.floor(Math.random()*defs.length)]}
function refreshMarket(){for(const start of [0,5]){const row=market.slice(start,start+5),kept=row.filter(Boolean);while(kept.length<5)kept.push(makeCard(refillDef()));for(let j=0;j<5;j++)market[start+j]=kept[j]}}

function at(r,c){return parcels.find(x=>x.r===r&&x.c===c)}
function value(p){let v=p.density;[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dr,dc])=>{const n=at(p.r+dr,p.c+dc);if(n)v+=n.density});if(p.water)v+=p.density;return v}
function state(){return JSON.stringify({players,turn,actions,mode,selected,population,jobs,setupDraft,draftPick,parcels,roads:[...roads],market})}
function restore(raw){const q=JSON.parse(raw);players.splice(0,players.length,...q.players);turn=q.turn;actions=q.actions;mode=q.mode;selected=q.selected;population=q.population;jobs=q.jobs;setupDraft=q.setupDraft;draftPick=q.draftPick;parcels.splice(0,parcels.length,...q.parcels);roads.clear();q.roads.forEach(x=>roads.add(x));market=q.market;pendingBuilding=null;pendingCouncil=null;roadSegments=0}
function snap(){try{history.push(state())}catch(e){console.error('Snapshot failed',e)}}
function undo(){if(actionStart){restore(actionStart);actionStart=null;if(history.length)history.pop();render();return}if(!history.length)return;restore(history.pop());render()}
function spendAction(){actions--}
function setMode(m){if(setupDraft||actions<=0)return;actionStart=null;mode=m;selected=null;pendingBuilding=null;pendingCouncil=null;roadSegments=0;render()}
function edgeKey(r,c,side){if(side==='N')return 'H:'+r+':'+c;if(side==='S')return 'H:'+(r+1)+':'+c;if(side==='W')return 'V:'+r+':'+c;return 'V:'+r+':'+(c+1)}
function edgeConnected(key){if(!roads.size)return true;const [o,a,b]=key.split(':'),r=+a,c=+b;const ends=o==='H'?[[r,c],[r,c+1]]:[[r,c],[r+1,c]];for(const k of roads){const [oo,aa,bb]=k.split(':'),rr=+aa,cc=+bb;const ee=oo==='H'?[[rr,cc],[rr,cc+1]]:[[rr,cc],[rr+1,cc]];if(ends.some(e=>ee.some(q=>q[0]===e[0]&&q[1]===e[1])))return true}return false}
function parcelEdges(x){return ['N','W',...(x.r===CONFIG.height-1?['S']:[]),...(x.c===CONFIG.width-1?['E']:[])].map(side=>{const key=edgeKey(x.r,x.c,side),built=roads.has(key);return `<span class="parcelroad ${side} ${built?'built':mode==='road'?'available':'hiddenedge'}" data-edge="${key}" title="${built?'Road':'Build road'}"></span>`}).join('')}
function render(){
 const draftPlayer=setupDraft?draftOrder[Math.min(draftPick,draftOrder.length-1)]:turn;
 const p=players[draftPlayer];
 document.querySelector('#app').innerHTML=`
 <header><div><h1>Civic Arbitrage</h1><p>Playas de México · v0.1 prototype · <b>Build ${BUILD_ID}</b></p></div><div class="turn"><span class="playerdisc p${p.i}"></span><b>${p.name}</b> · <strong>${setupDraft?`Starting draft — pick ${draftPick+1}/8`:`${actions}/2 actions`}</strong></div></header>
 <div class="actionbar ${setupDraft?'disabled':''}">${[['acquire','Acquire'],['sell','Sell'],['road','Build Road'],['zone','Zone / Rezone'],['building','Take Building']].map(([m,l])=>`<button class="${mode===m?'active':''}" data-mode="${m}">${l}</button>`).join('')}<button id="undo" class="undo" ${history.length?'':'disabled'}>↶ Undo</button></div>
 <main><section><div class="boardwrap"><div class="board">${parcels.map(x=>`<button class="parcel ${x.zone} ${x.water?'water':''} ${x.municipal?'civic':''} ${selected===x.id?'selected':''} ${pendingBuilding!==null&&legalBuild(x,market[pendingBuilding])?'legalbuild':''}" data-id="${x.id}"><span>${x.id}</span>${x.building?`<b class="building">${x.building}</b>`:''}${Number.isInteger(x.owner)?`<i class="ownerdisc p${x.owner}"></i>`:''}${x.density?`<em>${'●'.repeat(x.density)}</em>`:''}<small>${value(x)}</small>${!setupDraft?parcelEdges(x):''}</button>`).join('')}</div></div>
 <div class="sea">COAST — prototype geography</div>
 <div class="market"><h2>Building Market</h2>${[0,1].map(row=>`<div class="marketrow">${market.slice(row*5,row*5+5).map((c,j)=>c?`<button class="card" data-card="${row*5+j}"><b>${c.name}</b><span>${c.use}</span><strong>${'●'.repeat(c.density)}</strong><small>Subsidy ${c.coins} · Skip ${j}</small></button>`:`<div class="card card-empty" aria-label="Empty market slot"></div>`).join('')}</div>`).join('')}<div class="municipal-staging">Municipal staging — empty</div></div></section>
 <aside><h2><span class="playerdisc p${p.i}"></span>${p.name}</h2><div class="money">Hidden cash: $<b>${p.cash}</b></div><p>Tokens available: ${p.tokens}</p><h3>${setupDraft?'Starting parcel draft':'Action: '+modeLabel()}</h3><p>${setupDraft?'Choose any parcel except Municipal land. Existing private buildings may be acquired; pay $0 during the starting draft.':help()}</p>${mode==='zone'&&selected&&!pendingCouncil?zoneControls():''}${pendingCouncil?councilControls():''}${pendingBuilding!==null?buildingControls():''}${actions<=0&&!setupDraft?'<div class="noactions"><b>No more actions.</b> End your turn.</div>':''}<button id="end" ${setupDraft?'disabled':''}>${actions<=0?'End Turn':'End turn early'}</button><hr><h3>Growth</h3><p>Population ${population} / Jobs ${jobs}</p><p>Thresholds: 4 → 9 → 15</p></aside></main>`;
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('.parcel').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();parcelClick(el.dataset.id)}));document.querySelectorAll('.card').forEach(e=>e.onclick=()=>takeCard(+e.dataset.card));document.querySelectorAll('[data-edge]').forEach(e=>e.onclick=ev=>{ev.stopPropagation();buildRoad(e.dataset.edge)});document.querySelectorAll('[data-zone]').forEach(e=>e.onclick=()=>applyZone(e.dataset.zone,+e.dataset.density));document.querySelectorAll('[data-buildchoice]').forEach(e=>e.onclick=()=>buildingChoice(e.dataset.buildchoice));document.querySelectorAll('[data-council]').forEach(e=>e.onclick=()=>councilChoice(e.dataset.council));document.querySelector('#end').onclick=endTurn;document.querySelector('#undo').onclick=undo;
}
function modeLabel(){return {acquire:'Acquire parcel',sell:'Sell parcel',road:'Build Road',zone:'Zone / Rezone',building:'Take Building'}[mode]}
function help(){return {acquire:'Click any parcel not owned by a player. Existing private buildings do not block ownership. Municipal parcels cannot be owned. Pay current zoning/land value.',sell:'Click one of your parcels to sell it at current land value. Buildings and zoning remain.',road:'Place up to 2 connected public road segments for 1 action. Each segment costs $1. New roads must connect to the road network.',zone:'Click one of your parcels, then choose proposed zoning.',building:'Choose a card from either market row. Skip payments are automatic.'}[mode]}
function zoneControls(){return `<div class="zonecontrols">${['residential','commercial','municipal'].map(z=>`<div><b>${z}</b> ${[1,2,3].map(d=>`<button data-zone="${z}" data-density="${d}">${'●'.repeat(d)}</button>`).join('')}</div>`).join('')}</div>`}
function frontage(x){return ['N','S','E','W'].reduce((n,side)=>n+(roads.has(edgeKey(x.r,x.c,side))?1:0),0)+(x.water?1:0)}
function buildProblem(x,c){if(x.owner!==turn)return 'You do not own this parcel.';if(x.municipal)return 'Municipal land cannot take a private building.';if(x.zone!==c.use)return `Wrong zoning: this building requires ${c.use}.`;if(x.density<c.density)return `Zoning is too low: this building requires ${'●'.repeat(c.density)} density.`;if(frontage(x)<CONFIG.frontage[c.use][c.density])return `Not enough frontage: requires ${CONFIG.frontage[c.use][c.density]}, but this parcel has ${frontage(x)}.`;if(c.density>1){const needUse=c.use==='residential'?'commercial':'residential',needDensity=c.density-1;let found=false;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const n=at(x.r+dr,x.c+dc);if(n&&n.building&&n.zone===needUse&&n.density>=needDensity)found=true}if(!found)return `Missing nearby prerequisite: needs a built ${needUse} ${'●'.repeat(needDensity)} within the 8 surrounding parcels.`;}return null}
function legalBuild(x,c){return !buildProblem(x,c)}
function buildingControls(){const c=market[pendingBuilding];const legal=parcels.filter(x=>legalBuild(x,c));return `<div class="buildcontrols"><h3>Place ${c.name}</h3><p>${c.use} ${'●'.repeat(c.density)} · choose one of your parcels with matching zoning.</p><p>${legal.length?legal.map(x=>x.id).join(', ')+' highlighted on board.':'No legal parcel is currently available.'}</p><button data-buildchoice="discard">Discard for subsidy</button> <button data-buildchoice="cancel">Cancel</button></div>`}
function parcelClick(id){const x=parcels.find(q=>q.id===id);console.log('parcelClick',id,'draft',setupDraft,'pick',draftPick);if(setupDraft){const pi=draftOrder[draftPick],p=players[pi];if(!x)return alert('Draft error: parcel not found.');if(x.municipal)return alert('Municipal parcels cannot be privately owned.');if(Number.isInteger(x.owner))return alert('That parcel is already owned by a player.');snap();x.owner=pi;p.tokens=Math.max(0,p.tokens-1);if(!p.owned.includes(id))p.owned.push(id);draftPick+=1;if(draftPick>=draftOrder.length){setupDraft=false;turn=0;actions=CONFIG.actions;mode='acquire';selected=null;pendingBuilding=null;}render();return}if(mode==='building'&&pendingBuilding!==null){if(legalBuild(x,market[pendingBuilding]))return placeBuilding(x);return alert(buildProblem(x,market[pendingBuilding])||'That parcel is not a legal location for this building.');}if(x.municipal)return alert('Municipal parcels cannot be privately owned.');
 if(actions<=0)return;const p=players[turn];
 if(mode==='acquire'&&!Number.isInteger(x.owner)){const cost=value(x);if(p.tokens<1||p.cash<cost)return alert('Not enough cash or ownership tokens.');snap();x.owner=turn;p.tokens--;p.cash-=cost;p.owned.push(id);spendAction();render();return}
 if(mode==='sell'&&x.owner===turn){snap();p.cash+=value(x);p.tokens++;p.owned=p.owned.filter(q=>q!==id);x.owner=null;spendAction();render();return}
 if(mode==='zone'&&x.owner===turn){selected=id;render()}
}
function buildRoad(key){if(mode!=='road'||setupDraft||roads.has(key)||roadSegments>=2||(actions<=0&&roadSegments===0))return;const p=players[turn];if(p.cash<CONFIG.roadCost)return alert('Not enough cash.');if(!edgeConnected(key))return alert('New road must connect to the existing road network.');if(roadSegments===0){actionStart=state();history.push(actionStart);spendAction()}p.cash-=CONFIG.roadCost;roads.add(key);roadSegments++;if(roadSegments>=2)actionStart=null;render()}
function councilOdds(x,use,density){let yes=0;[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dr,dc])=>{const n=at(x.r+dr,x.c+dc),nd=n?n.density:0,nu=n?n.zone:'greenfield',diff=Math.abs(density-nd);yes+=diff===0?2:diff===1?1:0;yes+=nu===use?1:0});return yes}
function drawCouncil(yes){const bag=Array(yes).fill(1).concat(Array(12-yes).fill(0));for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]]}return bag.slice(0,7).reduce((a,b)=>a+b,0)}
function applyZone(use,density){const x=parcels.find(q=>q.id===selected);if(!x)return;actionStart=state();const yes=councilOdds(x,use,density),draw=drawCouncil(yes);pendingCouncil={id:x.id,use,density,yes,draw,cost:density};render()}
function councilControls(){const c=pendingCouncil;return '<div class="councilbox"><h3>Council draw</h3><p>Bag: '+c.yes+' Yes / '+(12-c.yes)+' No</p><p>Draw: <b>'+c.draw+' Yes / '+(7-c.draw)+' No</b></p>'+(c.draw>=4?'<button data-council="accept">Accept — PASSED</button>':'<button data-council="redraw">Pay $'+c.cost+' to redraw</button> <button data-council="accept">Accept failure</button>')+'</div>'}
function councilChoice(choice){const c=pendingCouncil;if(!c)return;const p=players[turn],x=parcels.find(q=>q.id===c.id);if(choice==='redraw'){if(p.cash<c.cost)return alert('Not enough cash to redraw.');p.cash-=c.cost;c.draw=drawCouncil(c.yes);render();return}if(c.draw>=4){x.zone=c.use;x.density=c.density}spendAction();selected=null;pendingCouncil=null;actionStart=null;render()}
function takeCard(i){if(mode!=='building'||actions<=0||setupDraft||pendingBuilding!==null)return;const p=players[turn],rowStart=i<5?0:5,pos=i-rowStart;if(p.cash<pos)return alert('Not enough cash to pay the market skip cost.');pendingBuilding=i;render()}
function commitMarket(i){const p=players[turn],rowStart=i<5?0:5,pos=i-rowStart,c=market[i];snap();for(let j=rowStart;j<i;j++)if(market[j])market[j].coins++;p.cash-=pos;p.cash+=c.coins;market[i]=null;return c}
function placeBuilding(x){const i=pendingBuilding,c=commitMarket(i),p=players[turn];if(x.building)x.building=null;x.building=c.name;p.cash+=CONFIG.buildPayout;if(c.use==='residential')population+=c.density;else if(c.use==='commercial')jobs+=c.density;c.coins=0;pendingBuilding=null;spendAction();render()}
function buildingChoice(choice){if(pendingBuilding===null)return;if(choice==='cancel'){pendingBuilding=null;render();return}if(choice==='discard'){const i=pendingBuilding,c=commitMarket(i);c.coins=0;pendingBuilding=null;spendAction();render()}}
function endTurn(){if(setupDraft)return;if(actionStart)actionStart=null;snap();pendingCouncil=null;roadSegments=0;refreshMarket();turn=(turn+1)%players.length;actions=CONFIG.actions;mode='acquire';selected=null;pendingBuilding=null;render()}
render();